# DO NOT CHANGE the "init" and "install" sections below

environment:
  global:
    USE_RTOOLS: true
    R_REMOTES_STANDALONE: true
  matrix:
    - TF_VERSION: 1.12.0
    - TF_VERSION: 1.13.1
  # - TF_VERSION: 1.14.0
  # - TF_VERSION: 2.0.0-rc0

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - R CMD INSTALL .
  - R -e "install.packages('devtools', repos = 'http://cran.rstudio.com'); devtools::install_github('rstudio/reticulate')"
  - R -e "tensorflow::install_tensorflow(method = 'conda', version = Sys.getenv('TF_VERSION'), extra_packages = 'IPython', envname = 'r-reticulate')"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
